name: Feature
on:
  push:
    branches: [feature]
    paths:
      - 'src/**'
      - '.github/workflows/**'
  pull_request:
    branches: [feature]
    paths:
      - 'src/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker And Run Container With SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_HOST }}
          username: ${{ secrets.TEST_USER }}
          key: ${{ secrets.TEST_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/dingtalk/dingtalk-vue/
            git pull origin test
            cnpm install
            npm run build:stage
            cd ~/dingtalk
            docker-compose build
            docker-compose up -d
            docker image prune -f
