name: Release
on:
  push:
    branches: [release]
    paths:
      - 'src/**'
      - '.github/workflows/**'
  pull_request:
    branches: [release]
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'package.json'
      - 'mysite.template'
      - 'Dockerfile'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker And Run Container With SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/dingtalk/dingtalk-vue/
            git pull origin master
            cnpm install
            npm run build
            cd ~/dingtalk
            docker-compose build
            docker-compose up -d
            docker image prune -f
