name: Release
on:
  push:
    branches: [release]
    paths:
      - 'src/**'
      - '.github/workflows/**'
  pull_request:
    branches: [release]
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'package.json'
      - 'mysite.template'
      - 'Dockerfile'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker With SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            if [ ! -d "dingtalk-app-release" ]; then
              git clone git@github.com:nju-softeng/dingtalk-app-build.git dingtalk-app-release
            fi
            git checkout release
            git pull origin
            cd dingtalk-app-build
            chmod +x build.sh
            ./build.sh -b main -t web